### ISSUE TITLE
Use up and down icons for easier floor switching

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map#1]
This is not very useful:

<img width="114" alt="" src="https://cloud.githubusercontent.com/assets/81942/13897988/7b81fb36-edc4-11e5-8557-bde8997fbfb6.png">

Up and down icons (similar to the + and - zoom icons) would be easier to use.

**Comment by xarsman** [comment]
I'll look into this one when/if I find some time

**Comment by BourbonCrow** [comment]
We could use this to make it maybe.
https://github.com/CliffCloud/Leaflet.EasyButton

http://danielmontague.com/projects/easyButton.js/v1/examples/

**Comment by 4544fa8d** [comment]
Hello :)

I've made plugin for leaflet which add those buttons. Feel free to pull [https://github.com/tibiamaps/tibia-map/pull/15](https://github.com/tibiamaps/tibia-map/pull/15)

Thanks :)
