### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Cavitt** [tibiamaps/tibia-map#10]
Hey, nice projects. I'm the original creator of the map (Syntax). Most of this seems to be my code, could you possibly give credits in your readme? Thanks in advance :)

"Original code taken from https://tibia.xyz/ developed by @Cavitt" or something.

**Comment by mathiasbynens** [comment]
Of course! I actually tried to find the person who wrote the base code but failed.

**Comment by mathiasbynens** [comment]
Fixed. If we ever meet, drinks on me! 👍

**Comment by Cavitt** [comment]
@mathiasbynens No worries, thanks man. Sounds good :D
