### ISSUE TITLE
Tibia Beta Support

### ISSUE THREAD

**Issue by EPuncker** [tibiamaps/tibia-map#12]
I don't know if this is the right place to post, but since today cipsoft made their beta client open to everyone, will there be a support for it in automap? it seems like the client has no way to export/import map between old and beta clients

**Comment by mathiasbynens** [comment]
<https://tibiamaps.io/blog/11-map-changes> answers your first question.

The Tibia 11 beta client automatically imports your existing `Automap` data.

**Comment by EPuncker** [comment]
actually I did install the tibia maps using the installer

![2016-07-05 13_14_50-automap](https://cloud.githubusercontent.com/assets/4684880/16591463/7c7667dc-42b2-11e6-95c3-151607f3c121.png)

but it did not appear ingame, that is why I posted here :P

![2016-07-05 13_15_45-tibia beta - umyna maril](https://cloud.githubusercontent.com/assets/4684880/16591501/ad5f59c6-42b2-11e6-9c29-4db821be7343.png)

**Comment by mathiasbynens** [comment]
The beta client imports the `Automap` data upon installation, so it has to be there before.

**Comment by EPuncker** [comment]
oh thanks for the info
