### ISSUE TITLE
Fix for pseudoFullscreen: False

### ISSUE THREAD

**Issue by BourbonCrow** [tibiamaps/tibia-map#13]
For ppl who cant run `'pseudoFullscreen': true` in map.js (i couldn't on my local website when i was testing.
and when i ran it as false it would cause a bug that when i enter and exit full screen 90% of the times it would bug out and the crosshair would dissapair and its off center when its generating so its looking really weird like generating offscreen and only showing half the map

This is my fix that ive tested and it works all time no issues!

the edit is in leaflet.fullscreen.css

```
/* Do not combine these two rules; IE will break. */
.leaflet-container:-webkit-full-screen {
  width:100%!important;
  height:100%!important;
  z-index: 99999;
  }
.leaflet-container.leaflet-fullscreen-on {
  width:100%!important;
  height:100%!important;
  z-index: 99999;
  }

```

with

```
 /* one selector per rule as explained here : http://www.sitepoint.com/html5-full-screen-api/ */
    .leaflet-container:-webkit-full-screen { width: 100% !important; height: 100% !important; z-index: 99999; }
    .leaflet-container:-ms-fullscreen { width: 100% !important; height: 100% !important; z-index: 99999; }
    .leaflet-container:full-screen { width: 100% !important; height: 100% !important; z-index: 99999; }
    .leaflet-container:fullscreen { width: 100% !important; height: 100% !important; z-index: 99999; }
```

Edit: made use of .leaflet-container instead of #map

**Comment by mathiasbynens** [comment]
How can I reproduce the issue you’re talking about? Which browser are you using?

**Comment by BourbonCrow** [comment]
I used google chrome i set 'pseudoFullscreen': false  in map.js  then when i press fullscreen and exit fullscreen it flips out like no croshair and other weird issues when you look around.. im using latest google chrome x64

**Comment by BourbonCrow** [comment]
ok i found the reason why that original code was broken.. i was to blind to see it 

 `.leaflet-container.leaflet-fullscreen-on {  `

its a . instead of a : 

should be 

` .leaflet-container:leaflet-fullscreen-on {  `

then it all works

**Comment by BourbonCrow** [comment]
this issue seems to be gone so this can be closed or removed or whatever guess it was a bug in old leaflet or something
