### ISSUE TITLE
Feature request: Add ability to browse historical maps.

### ISSUE THREAD

**Issue by 4544fa8d** [tibiamaps/tibia-map#14]
Hello :)

It would be nice if tibiamaps had additional date picker widget which would allow to view map like it was at selected date.

There was some locations in Tibia that aren't present anymore like "Flute Room" under Fibula or island Travora.

I think that every tibian archaeologist would love this feature

**Comment by tibiacentral** [comment]
If we are able to get the .map files I would be willing to implement this :)

**Comment by mathiasbynens** [comment]
The main difficulty in implementing this is getting the `*.map` files for each version (i.e. for every commit in this repo). That would be *a lot* of data that we’d have to store somewhere. It doesn’t seem feasible to me at this point.
