### ISSUE TITLE
Buggy behavior when double-clicking while fully zoomed in

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map#2]
To reproduce the issue, open e.g. https://tibiamaps.io/map#32332,32110,7:4 and double-click on the centered tile. This might be a Leaflet bug.

**Comment by xarsman** [comment]
This is a leaflet bug, I had a similar bug when we used version `0.7.x` of `Leaflet`. I had this solved by changing to `1.0-beta2` but it seems we lost that change somehow since I see we're now on `0.8-dev`.

TLDR: Updating the version should do the trick

**Comment by mathiasbynens** [comment]
#3 should be prioritized over this as per @xarsman’s comment.

**Comment by BourbonCrow** [comment]
I FIXED IT FINALLY AFTER READING API STUFF! sorry for caps but i'm happy.

```
map.on('dblclick', function() {
        if(map.getZoom() == 4) {
map.doubleClickZoom.disable(); 
        }
    });
```
that is what i did!
