### ISSUE TITLE
Proposal Markers

### ISSUE THREAD

**Issue by Bernardoow** [tibiamaps/tibia-map#21]
My proposal is to create the markers feacture.

Currently the map url consists of URL#part [coordinates]:part [zoom].

Ex: https://tibiamaps.io/map#32371,32200,7:0

With this functionality it would be URL#part [coordinates]: part [zoom]: part [bookmarks].
Ex: https://tibiamaps.io/map#32371,32200,7:0:32371,32200,7,2
Ex: https://tibiamaps.io/map#32371,32200,7:0:32371,32200,7,2|32361,32220,5,5

The markers would be the following data structure pos.x, pos.y, **floor**, marker.
Makers can be customized with images of monsters (I will check this possibility).

If there are more than one marker, they would be separated by a special character like pipe (|).

Can I implement?

**Comment by Bernardoow** [comment]
> I’m okay with supporting the in-game markers, but no others though (so e.g. no monster images). I’m worried about adding too much functionality at once without really needing it. We can always go back and discuss adding more markers later.

Sure.

> As for the URL format, I propose the following:
> https://tibiamaps.io/map#32371,32200,7:0&markers=[[32371,32200,7,2,"Optional marker title"],[32361,32220,5,5]]
> The idea is that we can call JSON.parse() on everything following &markers= to get the array of markers.

I liked =[[32371,32200,7,2,"Optional marker title"] and JSON.parse(). 
But I don't liked $markers, because this approach change pattern of url and how we handle that [1]. Another thing is how get information from query string is hard without use [2] URLSearchParams, thinking in browser compatibility, I will need code like [3].

For url format I prefere without queryparams. 
`https://tibiamaps.io/map#32371,32200,7:0:[[32371,32200,7,2,"Optional marker title"],[32361,32220,5,5]]`.

[1] https://github.com/tibiamaps/tibia-map/blob/8178bc02b4c84bb8b5e6bb4233c916b3bd1dd7a8/src/_js/map.js#L46
[2] https://developer.mozilla.org/pt-BR/docs/Web/API/URLSearchParams
[3] https://gomakethings.com/how-to-get-the-value-of-a-querystring-with-native-javascript/

**Comment by mathiasbynens** [comment]
The `&markers=` would still be part of the hash. It would just replace `:` as the delimiter. This is no more complex to implement than your suggestion.

**Comment by Bernardoow** [comment]
Ahhhhhh ! Now I get it !! Ok ! GREEEEEEAT IDEIA! I tried and it's works !! Great tip !!

For markers infos (Id and name),  I will use tibia wiki docs [1][2].

[1]http://tibia.wikia.com/wiki/File:Minimap_Symbols_Guide.png
[2]http://tibia.wikia.com/wiki/Template:Map_Marker

**Comment by mathiasbynens** [comment]
Please use the same marker icon IDs as the in-game client: https://tibiamaps.io/guides/map-file-format#map-marker-data

**Comment by Bernardoow** [comment]
I used ids from [1].
[1]https://tibiamaps.io/guides/map-file-format#map-marker-data.
