### ISSUE TITLE
Proposal: Make floor numbers easier to understand on level buttons

### ISSUE THREAD

**Issue by BourbonCrow** [tibiamaps/tibia-map#25]
instead of showing like 0-15

you could do so 0 is ground floor +1 is one floor up and -1 is 1 floor down and so on no idea if you like it or not and it wont affect cords or anything its just for easier knowing what floor your on when browsing the map
goes from -8 to +7
[example](https://i.imgur.com/Hy5i9fy.png)

code below is what i did to make it work you could try it out and see if you like 
leaflet.levelbuttons.js  around line 60~

```js
	_setFloor: function(floor) {
		var floor_button = L.DomUtil.get('floor_button');
		if (floor == 7) {
			floor_button.textContent = String(floor-7).padStart(2, '0');
		} else if (floor > 7) {
			floor_button.textContent = String(floor-7).padStart(2, '-');
		} else if (floor < 7) {
			floor_button.textContent = String(Math.abs(floor-7)).padStart(2, '+');
		} else {
		floor_button.textContent = String(floor).padStart(2, '0');
		}
	},
```

**Comment by BourbonCrow** [comment]
im still here lurking! gj keeping the website going btw!

**Comment by Bernardoow** [comment]
Can I do this? @mathiasbynens

**Comment by mathiasbynens** [comment]
@Bernardoow Yes, this would be awesome! Please go ahead :)

**Comment by Bernardoow** [comment]
PR #27
