### ISSUE TITLE
Block Point

### ISSUE THREAD

**Issue by Bernardoow** [tibiamaps/tibia-map#26]
When I will do some quest I check in some fansite spoiler about quest and then see and drag the map. In some cases, I clicked wrong at map and changed to new coordenate.

My proposal is add new urlParam to block the point.

**Comment by mathiasbynens** [comment]
I don’t really understand what is happening here. Can you link to an example?

If you click around on the map, you can always use the browser’s back button to go back to the earlier position. Does that help?

**Comment by Bernardoow** [comment]
Uhm .. using the button nothing happens.

Link: https://www.tibiawiki.com.br/wiki/Arachir_the_Ancient_One

Suppose I will check this boss, I use button to move floor to see where is this. I clicked wrong on map near of button. The position is lost.
