### ISSUE TITLE
Hidden Button 

### ISSUE THREAD

**Issue by Bernardoow** [tibiamaps/tibia-map#28]
When the floor reaches the limit, should we hide the button?

I created pr for this, maybe can be merged or closed !!

**Comment by BourbonCrow** [comment]
instead of making them hidden its better to take a light gray color like the + and - button has on the zoom looks way way better instead of having a button either go blank or dissapear witch looks stupid currently @Bernardoow @mathiasbynens

**Comment by Bernardoow** [comment]
I did it now, the better, right?
![tibia_map_floor](https://user-images.githubusercontent.com/4077212/36416667-7d6d8514-1608-11e8-9eb8-3c90f60effb9.png)

**Comment by BourbonCrow** [comment]
Very beatiful @Bernardoow also gj on adding the esier to read floor level your code was much more beatiful then mine i have no idea wth im doing im just doing random stuff and hope it works hah
