### ISSUE TITLE
Feature Request: display map file coordinates on website Map Viewer

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map#31]
I think it would be very helpful if the website map viewer showed the corresponding map file coordinates of the selected location. It would make searching for the required files to update an area much easier.

**Comment by mathiasbynens** [comment]
As a workaround until this is added, you can copy the coordinates from the URL. It updates every time you change floors or click anywhere on the map.

**Comment by mathiasbynens** [comment]
Oooh I see what you mean. I run into this myself all the time, where I do a manual `Math.floor(x/256)*256` for each of the `x` and `y` coordinates.

**Comment by mathiasbynens** [comment]
I’ve pushed a commit that logs the “minimap ID” (let’s call it that) in the DevTools Console every time you click the map.

[To open the console in Chrome](https://developers.google.com/web/tools/chrome-devtools/console/):

> Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).

Other browsers have similar functionality.

I’m still thinking of how to show this in the UI somewhere, but for now this is a good enough workaround.

**Comment by LeeKunTibia** [comment]
I can work with that, thanks for the quick solution! I already noticed one area missing from yesterday's data and the feature will be useful to get it. :)

**Comment by mathiasbynens** [comment]
I’m gonna close this issue, as the current solution is sufficient for the time being.
