### ISSUE TITLE
Feature Request: Show map markers with labels

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map#32]
I was navigating the map today and found myself wondering what was island that was. The Map could have an option to show markers (the client markers would be enough), and then when hovering a popup with the name of the place would be displayed, possibly with a link to TibiaWiki. 

Since it would be very time consuming to add marks at first, ideally they should be stored in a text format (e.g. json) so we can even edit and add new marks right here on GitHub, and then make the pull requests. I was thinking of something like:

```
{
 "X": 32078,
 "Y": 32441,
 "Z": 7,
 "Type": "Town",  // The marker type would be defined by this. 
 "Label": "Meluna",
 "Link": true
} 
```

This boolean true/false mode would only work if the label is identical to the Wiki page, but I think it's much simpler than parsing some sort of markdown inside the label, for example (but that would be ideal). 

With this we could identify even small rooms, for example the exact room of each Inquisition boss. Since this could also pollute the map, perhaps there could a way to filter the markers you want to see (Towns, Boss, Hunting Area, etc). 

I don't think I can do this by myself from scratch but I can try to help improving and of course adding the markers.

**Comment by mathiasbynens** [comment]
We could potentially re-use the JSON files that stores the actual marker data: https://github.com/tibiamaps/tibia-map-data/blob/master/data/floor-07-markers.json

**Comment by Bernardoow** [comment]
A few months ago I wrote this: https://github.com/Bernardoow/tibia-map/commits/markers. This can give a ideia how is the map with markers.

**Comment by mathiasbynens** [comment]
This has been live for a while now!
