### ISSUE TITLE
Tiling issue in google chrome

### ISSUE THREAD

**Issue by BourbonCrow** [tibiamaps/tibia-map#5]
![](https://cloud.githubusercontent.com/assets/81942/14587234/04a142c6-04b0-11e6-910e-87cf0af27cac.png)

Not sure how to discribe it it randomly appaears when moving around quick/updating location with cordinates #12314,13123:4 that kind of stuff if youy get what i mean and it fixes it self when zooming in and looks weird again when zooming out

**Comment by mathiasbynens** [comment]
This sounds like something that, like #2, *might* be fixed by upgrading Leaflet.

In other words, I think #3 should be prioritized over this.

**Comment by BourbonCrow** [comment]
also seems to be fixed by upgrading leaflet so im closing this
