### ISSUE TITLE
Feature request: tile friction data

### ISSUE THREAD

**Issue by kik-tibia** [tibiamaps/tibia-map#50]
Sometimes I want to know the friction of the floor in a particular area of the map. To do this, I have to open my local minimap folder, find the correct waypoint image and inspect it manually.

It would be useful if there was a button on the website to toggle between regular map mode and friction mode. If you are in friction mode, instead of displaying the `Minimap_Color` tiles, it would display the `Minimap_WaypointCost` tiles instead, and a label would tell you the friction of the selected coordinate.

Is this something you would consider adding?
Thanks!

**Comment by kik-tibia** [comment]
I just noticed that you added this feature earlier this year (except the friction label), many thanks!

**Comment by mathiasbynens** [comment]
Thanks again for suggesting it! See also #51 which is closer to your actual request but still left to do.
