### ISSUE TITLE
Fix for browser history being "spammed"

### ISSUE THREAD

**Issue by BourbonCrow** [tibiamaps/tibia-map#8]
This bug was only happening in Chrome as far as i noticed but this fixes it for all browsers it seems

```js
	var setUrlPosition = function(coords, forceHash) {
		var url = '#' + coords.x + ',' + coords.y + ',' + coords.floor + ':' + coords.zoom;
		if (
			forceHash ||
			(location.hash && location.hash != url)
		) {
			window.history.pushState(null, null, url);
		}
	};
```

Change that to 

```js
	var setUrlPosition = function(coords, forceHash) {
		var url = '#' + coords.x + ',' + coords.y + ',' + coords.floor + ':' + coords.zoom;
		if (
			forceHash ||
			(location.hash && location.hash != url)
		) {
			window.history.replaceState(null, null, url);
		}
	};
```
and it all works (tested in Chrome and Microsoft Edge, IE11)

**Comment by mathiasbynens** [comment]
This is intentional. Every time you highlight a specific location, the URL is updated and we want you to be able to go back to the previously highlighted spot.

**Comment by mathiasbynens** [comment]
One thing we can improve though is to avoid adding a new history entry when it’s the same as the previous entry.

**Comment by BourbonCrow** [comment]
ok but if this  is intentional shouldnt window.history.pushState(null, null, url); be removed? cause what that is doing is removing all history.. it works in all browswerds except chrome it seems.. replace state fixed it for chrome

**Comment by mathiasbynens** [comment]
> One thing we can improve though is to avoid adding a new history entry when it’s the same as the previous entry.

Done in 3d03df0.
